stages:
  - deploy
deploy_production:
  stage: deploy
  script:
    - rsync -av -e 'ssh' * proactive@109.205.182.6:/var/www/html/iklinika.uz/ --no-perms --no-owner --no-group --omit-dir-times
    - ssh proactive@109.205.182.6 "cd /var/www/html/iklinika.uz/ && YII_ENV=prod php ./init --env=Production --overwrite=All && composer install && YII_ENV=prod php ./yii migrate/up --interactive=0"
  environment:
    name: production
    url: https://www.iklinika.uz/
  only:
    - master
